service :

schedule :
   #test :
      #class : balam.exof.scheduler.TestSchedule
      #cronExpression : 0/5 * * * * ?
      #duplicateExecution : no
      #parameterGroup :
         #- parameter :
            #a1 : b34
            #c1 : d34
         #- parameter : 
            #a2 : b2
            #c2 : d2
      